export const SET_PLAYING_SHOW = 'SET_PLAYING_SHOW' // 设置当前是否显示转盘播放页面
export const SET_PLAY_SATE = 'SET_PLAY_SATE' // 设置当前的播放状态
export const SET_FULL_SCREEN = 'SET_FULL_SCREEN' // 设置当前的播放器的状态，是大还是小
export const SET_AUDIO_INDEX = 'SET_AUDIO_INDEX' // 设置当前的播放歌曲是第几个，索引值
export const SET_AUDIO_LIST = 'SET_AUDIO_LIST' // 设置当前的播放列表的展示
export const SET_TAB_STATSU = 'SET_TAB_STATSU'
export const SET_SMALLAUDIO_STATUS = "SET_SMALLAUDIO_STATUS" //设置是否显示小的播放器
export const SET_PLAY_LIST = 'SET_PLAY_LIST' // 设置当前的播放列表
export const GET_SONGS = 'GET_SONGS'//获取当前歌曲
export const SET_AUDIO_MODE = 'SET_AUDIO_MODE' // 设置当前的播放模式
export const SET_LINK_PAGE = 'SET_LINK_PAGE' // 将load返回默认的true
export const GET_USERINFO="GET_USERINFO" //获取用户详情
export const LOGIN_STATE = 'LOGIN_STATE' // 登陆状态
export const TIME_STATE='TIME_STATE'//记录播放时间
export const RULELYRIC="RULELYRIC" //歌词存储起来
export const CURRENT_INDEX="CURRENT_INDEX"//径路当前索引
export const GETUSER_SONGURL='GETUSER_SONGURL' //获取url